# Podfile for Votis Wallet iOS App
# Generated for Kotlin Multiplatform Mobile project

platform :ios, '13.0'
use_frameworks!

target 'iosApp' do
  # Google Sign-In for authentication
  pod 'GoogleSignIn', '~> 7.0'
  
  # The Kotlin Multiplatform framework will be added automatically
  # via the Kotlin CocoaPods Gradle plugin
end

# Configure post_install to fix common issues
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
